gcc -Wextra -Werror -Wall group_tests/test_libc.c ../*.c group_tests/subtests/* -I ../ -o test_libc
gcc -Wextra -Werror -Wall group_tests/test_putx.c ../*.c group_tests/subtests/* -I ../ -o test_putx
gcc -Wextra -Werror -Wall group_tests/test_sup2.c ../*.c group_tests/subtests/* -I ../ -o test_sup2
gcc -Wextra -Werror -Wall single_tests/test_memset.c ../*.c -I ../ -o exe/memset
gcc -Wextra -Werror -Wall single_tests/test_bzero.c ../*.c -I ../ -o exe/bzero
gcc -Wextra -Werror -Wall single_tests/test_memcpy.c ../*.c -I ../ -o exe/memcpy
gcc -Wextra -Werror -Wall single_tests/test_memccpy.c ../*.c -I ../ -o exe/memccpy
gcc -Wextra -Werror -Wall single_tests/test_memmove.c ../*.c -I ../ -o exe/memmove
gcc -Wextra -Werror -Wall single_tests/test_memchr.c ../*.c -I ../ -o exe/memchr
gcc -Wextra -Werror -Wall single_tests/test_memcmp.c ../*.c -I ../ -o exe/memcmp
gcc -Wextra -Werror -Wall single_tests/test_strlen.c ../*.c -I ../ -o exe/strlen
gcc -Wextra -Werror -Wall single_tests/test_strdup.c ../*.c -I ../ -o exe/strdup
gcc -Wextra -Werror -Wall single_tests/test_strcpy.c ../*.c -I ../ -o exe/strcpy
gcc -Wextra -Werror -Wall single_tests/test_strncpy.c ../*.c -I ../ -o exe/strncpy
gcc -Wextra -Werror -Wall single_tests/test_strcat.c ../*.c -I ../ -o exe/strcat
gcc -Wextra -Werror -Wall single_tests/test_strncat.c ../*.c -I ../ -o exe/strncat
gcc -Wextra -Werror -Wall single_tests/test_strlcat.c ../*.c -I ../ -o exe/strlcat
gcc -Wextra -Werror -Wall single_tests/test_strchr.c ../*.c -I ../ -o exe/strchr
gcc -Wextra -Werror -Wall single_tests/test_strrchr.c ../*.c -I ../ -o exe/strrchr
gcc -Wextra -Werror -Wall single_tests/test_strstr.c ../*.c -I ../ -o exe/strstr
gcc -Wextra -Werror -Wall single_tests/test_strnstr.c ../*.c -I ../ -o exe/strnstr
gcc -Wextra -Werror -Wall single_tests/test_strcmp.c ../*.c -I ../ -o exe/strcmp
gcc -Wextra -Werror -Wall single_tests/test_strncmp.c ../*.c -I ../ -o exe/strncmp
gcc -Wextra -Werror -Wall single_tests/test_atoi.c ../*.c -I ../ -o exe/atoi
gcc -Wextra -Werror -Wall single_tests/test_isalpha.c ../*.c -I ../ -o exe/isalpha
gcc -Wextra -Werror -Wall single_tests/test_isdigit.c ../*.c -I ../ -o exe/isdigit
gcc -Wextra -Werror -Wall single_tests/test_isalnum.c ../*.c -I ../ -o exe/isalnum
gcc -Wextra -Werror -Wall single_tests/test_isascii.c ../*.c -I ../ -o exe/isascii
gcc -Wextra -Werror -Wall single_tests/test_isprint.c ../*.c -I ../ -o exe/isprint
gcc -Wextra -Werror -Wall single_tests/test_toupper.c ../*.c -I ../ -o exe/toupper
gcc -Wextra -Werror -Wall single_tests/test_tolower.c ../*.c -I ../ -o exe/tolower
gcc -Wextra -Werror -Wall single_tests/test_memalloc.c ../*.c -I ../ -o exe/memalloc
gcc -Wextra -Werror -Wall single_tests/test_memdel.c ../*.c -I ../ -o exe/memdel
gcc -Wextra -Werror -Wall single_tests/test_strnew.c ../*.c -I ../ -o exe/strnew
gcc -Wextra -Werror -Wall single_tests/test_strdel.c ../*.c -I ../ -o exe/strdel
gcc -Wextra -Werror -Wall single_tests/test_strclr.c ../*.c -I ../ -o exe/strclr
gcc -Wextra -Werror -Wall single_tests/test_striter.c ../*.c -I ../ -o exe/striter
gcc -Wextra -Werror -Wall single_tests/test_striteri.c ../*.c -I ../ -o exe/striteri
gcc -Wextra -Werror -Wall single_tests/test_strmap.c ../*.c -I ../ -o exe/strmap
gcc -Wextra -Werror -Wall single_tests/test_strmapi.c ../*.c -I ../ -o exe/strmapi
gcc -Wextra -Werror -Wall single_tests/test_strequ.c ../*.c -I ../ -o exe/strequ
gcc -Wextra -Werror -Wall single_tests/test_strnequ.c ../*.c -I ../ -o exe/strnequ
gcc -Wextra -Werror -Wall single_tests/test_strsub.c ../*.c -I ../ -o exe/strsub
gcc -Wextra -Werror -Wall single_tests/test_strjoin.c ../*.c -I ../ -o exe/strjoin
gcc -Wextra -Werror -Wall single_tests/test_strtrim.c ../*.c -I ../ -o exe/strtrim
gcc -Wextra -Werror -Wall single_tests/test_strsplit.c ../*.c -I ../ -o exe/strsplit
gcc -Wextra -Werror -Wall single_tests/test_itoa.c ../*.c -I ../ -o exe/itoa
gcc -Wextra -Werror -Wall single_tests/test_putchar.c ../*.c -I ../ -o exe/putchar
gcc -Wextra -Werror -Wall single_tests/test_putstr.c ../*.c -I ../ -o exe/putstr
gcc -Wextra -Werror -Wall single_tests/test_putendl.c ../*.c -I ../ -o exe/putendl
gcc -Wextra -Werror -Wall single_tests/test_putnbr.c ../*.c -I ../ -o exe/putnbr
gcc -Wextra -Werror -Wall single_tests/test_putchar_fd.c ../*.c -I ../ -o exe/putchar_fd
gcc -Wextra -Werror -Wall single_tests/test_putstr_fd.c ../*.c -I ../ -o exe/putstr_fd
gcc -Wextra -Werror -Wall single_tests/test_putendl_fd.c ../*.c -I ../ -o exe/putendl_fd
gcc -Wextra -Werror -Wall single_tests/test_putnbr_fd.c ../*.c -I ../ -o exe/putnbr_fd
gcc -Wextra -Werror -Wall single_tests/test_lstnew.c ../*.c -I ../ -o exe/lstnew
gcc -Wextra -Werror -Wall single_tests/test_lstdelone.c ../*.c -I ../ -o exe/lstdelone
gcc -Wextra -Werror -Wall single_tests/test_lstdel.c ../*.c -I ../ -o exe/lstdel
gcc -Wextra -Werror -Wall single_tests/test_lstadd.c ../*.c -I ../ -o exe/lstadd
gcc -Wextra -Werror -Wall single_tests/test_lstiter.c ../*.c -I ../ -o exe/lstiter
gcc -Wextra -Werror -Wall single_tests/test_lstmap.c ../*.c -I ../ -o exe/lstmap
